<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1LV8K5I" failures="2" tests="21" name="com.practo.tests.TestHomePage" time="354.776" errors="0" timestamp="2021-03-23T23:37:19 IST" skipped="0">
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_001" time="3.501"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_002" time="16.219"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_003" time="14.216"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_004" time="27.767"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_005" time="25.588"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_006" time="34.580"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_007" time="25.579"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_008" time="96.310"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_009" time="13.708"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_010" time="5.853"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_011" time="7.424"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_012" time="7.421"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_013" time="12.487"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_014" time="7.250"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_015" time="8.523"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_016" time="9.269"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_017" time="7.537"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_018" time="7.508"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_019" time="7.299"/>
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_020" time="8.074">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.practo.tests.TestHomePage.TC_FH_020(TestHomePage.java:501)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_FH_020 -->
  <system-out/>
  <testcase classname="com.practo.tests.TestHomePage" name="TC_FH_021" time="8.663">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.practo.tests.TestHomePage.TC_FH_021(TestHomePage.java:526)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_FH_021 -->
  <system-out/>
</testsuite> <!-- com.practo.tests.TestHomePage -->
